// <auto-generated />
using System;
using DidierGuerrero_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DidierGuerrero_Examen1P.Migrations
{
    [DbContext(typeof(DidierGuerrero_Examen1PContext))]
    [Migration("20231025133156_DidierGuerreroDB")]
    partial class DidierGuerreroDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DidierGuerrero_Examen1P.Models.DidierGuerrero__Tabla", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("MdgMayorEdad")
                        .HasColumnType("bit");

                    b.Property<int>("dgEntradasDisponibles")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dgFechaPelicula")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("dgNombrePelicula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("dgPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("DidierGuerrero__Tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
